### ISSUE TITLE
window coverings type as option

### ISSUE THREAD

**Issue by PePeUser** [jmaferreira/homebridge-garage-door-shelly1#3] opened 2021-01-24 20:38 UTC
Hi,
if possible, it would be great if the accessories can be shown as window coverings instead garage doors as selectable option.

It works great with shelly2.5 in uncalibrated mode.

**Comment by jmaferreira** [comment] 2021-01-30 19:25
Hi,

This is a duplicate of #1 . I'm going to close this one.

**Closed by jmaferreira** 2021-01-30 19:25 UTC
